perl-5.26.0 compatibility
hatukanezumi/MIME-Charset pull request #1
Opened 2017-04-01 01:51 UTC by jkeenan

In Perl 5.26.0, '.' will no longer be found by default in @INC.  This patch
adjusts Makefile.PL to enable configuration in this case.

For:  https://rt.cpan.org/Ticket/Update.html?id=116459

2017-04-06 04:38 UTC, hatukanezumi requested changes
I consider your PR does not solve the issue described in RT#116459.  Could you please change commit message and submit PR again?

Thank you for cooperation.

2017-04-06 11:40 UTC, jkeenan commented
If you've applied the Debian patch then mine probably won't be needed.  Thanks for reviewing.

2017-04-06 11:40 UTC, closed without merging

2017-04-07 19:16 UTC, kentfredric commented
The debian patch fixes something entirely different.
Installation is still broken on 5.26

Configuring MIME-Charset-1.012.1 ... Can't locate inc/Module/Install.pm in @INC (you may need to install the inc::Module::Install module) (@INC contains: /home/kent/perl5/perlbrew/perls/5.25.11-nossp-sip13-nopmc-nodot/lib/site_perl/5.25.11/x86_64-linux /home/kent/perl5/perlbrew/perls/5.25.11-nossp-sip13-nopmc-nodot/lib/site_perl/5.25.11 /home/kent/perl5/perlbrew/perls/5.25.11-nossp-sip13-nopmc-nodot/lib/5.25.11/x86_64-linux /home/kent/perl5/perlbrew/perls/5.25.11-nossp-sip13-nopmc-nodot/lib/5.25.11) at Makefile.PL line 3.

2017-04-08 08:39 UTC, ikedas commented
kentfredric is right.  I just wish jkeenan to correct commit message, not commit itself.